version: '3.8'
services:
  db:
    image: dainalfek/postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    # volumes: 
    #   - ./db:/var/lib/postgresql/data
    #   - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
  backend:
    image: dainalfek/tic-tac-toe_backend:latest
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - "./backend:/backend"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5432
  frontend:
    image: dainalfek/tic-tac-toe_frontend:latest
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    # volumes:
    #   - ./frontend:/app
    command: npm start
